name: npprompt_env
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.4.0
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - cpuonly=2.0
  - cpython=3.10.19
  - ffmpeg=4.4.2
  - filelock=3.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.6
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.11
  - intel-openmp=2022.1.0
  - jinja2=3.1.6
  - jpeg=9e
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.17
  - libdrm=2.4.125
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libpciaccess=0.18
  - libpng=1.6.50
  - libsqlite=3.50.4
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtasn1=4.20.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=2.41.2
  - libva=2.18.0
  - libvpx=1.11.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markupsafe=3.0.3
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.8.1
  - networkx=3.4.2
  - openh264=2.3.0
  - openjpeg=2.5.0
  - openssl=3.5.4
  - pillow=9.4.0
  - pip=25.2
  - pthread-stubs=0.4
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.19
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.3
  - readline=8.2
  - requests=2.32.5
  - setuptools=80.9.0
  - svt-av1=1.2.0
  - tk=8.6.13
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - typing_extensions=4.15.0
  - urllib3=2.5.0
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - anyio==4.11.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - click==8.3.0
      - datasets==2.10.0
      - dill==0.3.6
      - exceptiongroup==1.3.0
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.11.1
      - joblib==1.5.2
      - multidict==6.7.0
      - multiprocess==0.70.14
      - nltk==3.9.2
      - numpy==1.26.4
      - packaging==25.0
      - pandas==2.3.3
      - propcache==0.4.1
      - protobuf==6.33.0
      - pyarrow==11.0.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - regex==2025.10.23
      - responses==0.18.0
      - rouge==1.0.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentence-transformers==2.2.2
      - sentencepiece==0.2.1
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.13.1
      - tensorboardx==2.6.4
      - threadpoolctl==3.6.0
      - tokenizers==0.12.1
      - tqdm==4.67.1
      - transformers==4.20.0
      - tzdata==2025.2
      - xxhash==3.6.0
      - yacs==0.1.8
      - yarl==1.22.0
prefix: /home/ink/miniconda3/envs/npprompt_env
